### ISSUE TITLE
[Linux] Bulk Recovery Fails when CSV File Resides in Directory with Uppercase Characters in Name

### ISSUE THREAD

**Issue by Revysu** [Shishkebaboo/VodRecovery#12]
**Description:**
When attempting to perform bulk clip recovery on Linux with a CSV file located in a directory whose name contains uppercase characters, the program fails to locate the file. This occurs because the program searches for the file using the directory path with all lowercase characters, instead of using the actual case of the directory name.

**Steps to reproduce:**
1. Create a directory with uppercase characters in its name, for example "TestDirectory".
2. Place a CSV file in the directory.
3. Attempt to run bulk recovery on the CSV file.

**Expected result:**
The program should be able to locate and recover the CSV file, regardless of the case of characters in the directory name.

**Actual result:**
The program fails to locate the CSV file and returns `FileNotFoundError: [Errno 2] No such file or directory: '/home/revysu/testdirectory/csv.csv'`

**Proposed solution:**
Removing `remove_whitespace_and_lowercase` at line 725 fix this issue.

**Comment by Shishkebaboo** [comment]
@Revysu That is not the reason.. it is failing.  The reason its failing is because of the default/download directories which are defined in the config file. 

By default the script looks for a path such as ```/home/revysu/documents/``` on linux OR ```C:\Users\USER\Documents\``` on windows.

If you want this to work correctly... Create the directory in your documents folder then try it again and it should work as expected. 

Do not change the name of the csv file - The script uses the name for different things to minimize the amount of user input required and to always generate the proper output.

**Comment by Revysu** [comment]
- I created a directory named `TestDirectory` under the `documents` folder
- Full path is: `/home/revysu/documents/TestDirectory/originalname.csv`
(Ignore the .csv name it's juste for the example, on my disk it's the original one from gnomesully)
Still fails with the same `FileNotFoundError: [Errno 2] No such file or directory: '/home/revysu/documents/testdirectory/originalname.csv'`... Well of course, there is no `testdirectory` on my system but `TestDirectory` instead.

This is because Linux distinguishes between lowercase and uppercase letters in file and directory names, unlike Windows. Although I could simply create a directory with all lowercase letters to avoid the issue, I believe it's important to have the flexibility to save files in any location regardless of case sensitivity.

**Comment by Shishkebaboo** [comment]
@Revysu I have the following file path.. C:\Users\USER\Documents\Sullygnome CSV which uses uppercase and it works as expected. Ill look though see if I can find why its happening.

**Comment by Revysu** [comment]
Again, I believe it's because there is `remove_whitespace_and_lowercase` before `(input("Enter full path of sullygnome CSV file: ").replace('"', ''))` (line 725). The code works on Windows due to differences in how file and folder names are treated compared to Linux. I was able to resolve the issue by removing that part of the code, and now the program successfully finds the CSV file in the correct folder. I guess if you remove it you'll get the same error in Windows.

Sure thing:
```
python3 RecoverVod.py
2) Recover Clips
3) Bulk recover clips from SullyGnome CSV export
1) Single CSV file
Enter full path of sullygnome CSV file: "/home/revysu/documents/TestDirectory/ogname.csv"
Do you want to download all clips recovered (Y/N)? y
1) Default ([VodID]-offset-[interval])
Traceback (most recent call last):
  File "/home/revysu/VodRecovery/RecoverVod.py", line 918, in <module>
    run_script()
  File "/home/revysu/VodRecovery/RecoverVod.py", line 867, in run_script
    bulk_clip_recovery()
  File "/home/revysu/VodRecovery/RecoverVod.py", line 743, in bulk_clip_recovery
    for vod_id, values in parse_clip_csv_file(csv_file_path).items():
  File "/home/revysu/VodRecovery/RecoverVod.py", line 641, in parse_clip_csv_file
    csv_file = open(file_path, "r+")
FileNotFoundError: [Errno 2] No such file or directory: '/home/revysu/documents/testdirectory/originalname.csv'
```

**Comment by Shishkebaboo** [comment]
@Revysu I don't have a linux machine so its hard to test but I believe the issue is what your suggesting... its the  suggested solution that Im not so sure about.

Can you try replacing line 641 with the following:

csv_file = open(remove_whitespace_and_lowercase(file_path), "r+")

**Comment by Revysu** [comment]
Yep I'm not sure either for the solution, you'll have to dig by yourself has I know nothing about python...

Still the same unfortunately
```
Traceback (most recent call last):
  File "/home/revysu/VodRecovery/RecoverVod.py", line 918, in <module>
    run_script()
  File "/home/revysu/VodRecovery/RecoverVod.py", line 867, in run_script
    bulk_clip_recovery()
  File "/home/revysu/VodRecovery/RecoverVod.py", line 743, in bulk_clip_recovery
    for vod_id, values in parse_clip_csv_file(csv_file_path).items():
  File "/home/revysu/VodRecovery/RecoverVod.py", line 641, in parse_clip_csv_file
    csv_file = open(remove_whitespace_and_lowercase(file_path), "r+")
FileNotFoundError: [Errno 2] No such file or directory: '/home/revysu/documents/testdirectory/ogname.csv'
```

**Comment by Shishkebaboo** [comment]
Yep, Might have to download an abuntu machine so im able to test it properly.

**Comment by Revysu** [comment]
I've reviewed the `remove_whitespace_and_lowercase` function, and based on my tests on both Windows and Linux, removing this function from the program (specifically from line 725) did not cause any issues in finding the correct path to the required files.

To test this, I used (from Windows 10) the `Recover Clips` > `Bulk recover clips from SullyGnome CSV export` > `Single CSV file` options in the program, and created two folders with different casing in their names: one with an uppercase folder name in `C:\Users\Win\Documents\Syncthing\csv.csv`, 
and another with a lowercase folder name in `C:\Users\Win\Pictures\test\csv.csv`
I tested both folders and confirmed that the program was able to locate the files in each of them as expected, even without using the `remove_whitespace_and_lowercase` function.

Therefore, while the `remove_whitespace_and_lowercase` function may be useful for other parts of the code, it does not appear to be necessary for the purpose of finding the correct path to the .csv

However if you still want to test it on ubuntu and you're not already familiar with Linux, it might take a long time to find an alternative solution so in the meantime, it might be helpful to let other Linux users know in the README that a "fix" is available if they experience the same problem.

Anyway, thanks for this great tool

**Comment by Shishkebaboo** [comment]
After researching this a bit.. I think this is going to take a fairly major refactor as I need to identify the users operating system then code based off that. 

Therefore this issue will be considered an enhancement issue and may not be fixed in the near future.
