### ISSUE TITLE
strptime error with v1.0.3.0

### ISSUE THREAD

**Issue by mepherion** [Shishkebaboo/VodRecovery#30]
When using either TwitchTracker or StreamCharts URL as the Website Video Recovery option, python throws an error message regarding `strptime()`

I am having no issues with the previous version though.

I am using python 3.11.5 on Windows

```console
>python3 vod_recovery.py 
WELCOME TO VOD RECOVERY

1) VOD Recovery
2) Clip Recovery
3) Unmute M3U8 File
4) Verify Segment Availability
5) Create M3U8 File (Comments out invalid segments)
6) Download M3U8 File (.MP4 Extension)
7) Help
8) Exit

Choose an option: 1
1) Single Video Recovery
2) Bulk video Recovery from SullyGnome CSV Export
3) Exit

Select VOD Recovery Mode: 1
1) Manual Recovery
2) Website Video Recovery
3) Exit

Select VOD Recovery Method: 2
Enter Twitchtracker/Streamscharts/Sullygnome url:  https://twitchtracker.com/helpinghans/streams/39932421717
Error: Unable to fetch webpage. Status code: 403
Searching for videos...
Traceback (most recent call last):
  File "vod_recovery.py", line 961, in <module>
    run_vod_recover()
  File "vod_recovery.py", line 882, in run_vod_recover

    website_vod_recover()
  File "vod_recovery.py", line 345, in website_vod_rec
over
    m3u8_link = vod_recover(streamer, video_id, parse_datetime_twitchtracker(tracker_url))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "vod_recovery.py", line 643, in vod_recover
    vod_age = calculate_days_since_broadcast(timestamp)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "vod_recovery.py", line 147, in calculate_days_
since_broadcast
    vod_age = datetime.today() - datetime.strptime(start_timestamp, '%Y-%m-%d %H:%M:%S')
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not None
```

```console
>python3 vod_recovery.py 
WELCOME TO VOD RECOVERY

1) VOD Recovery
2) Clip Recovery
3) Unmute M3U8 File
4) Verify Segment Availability
5) Create M3U8 File (Comments out invalid segments)
6) Download M3U8 File (.MP4 Extension)
7) Help
8) Exit

Choose an option: 1
1) Single Video Recovery
2) Bulk video Recovery from SullyGnome CSV Export
3) Exit

Select VOD Recovery Mode: 1
1) Manual Recovery
2) Website Video Recovery
3) Exit

Select VOD Recovery Method: 2
Enter Twitchtracker/Streamscharts/Sullygnome url:  https://streamscharts.com/channels/helpinghans/streams/39932421
717
Failed to fetch webpage after 10 retries.
Searching for videos...
Traceback (most recent call last):
  File "vod_recovery.py", line 961, in <module>
    run_vod_recover()
  File "vod_recovery.py", line 882, in run_vod_recover

    website_vod_recover()
  File "vod_recovery.py", line 336, in website_vod_rec
over
    m3u8_link = vod_recover(streamer, video_id, parse_datetime_streamscharts(tracker_url))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "vod_recovery.py", line 643, in vod_recover
    vod_age = calculate_days_since_broadcast(timestamp)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "vod_recovery.py", line 147, in calculate_days_
since_broadcast
    vod_age = datetime.today() - datetime.strptime(start_timestamp, '%Y-%m-%d %H:%M:%S')
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: strptime() argument 1 must be str, not None
```

**Comment by Shishkebaboo** [comment]
@mepherion status code 403 implies you are getting blocked from the website itself most likely bot detection.

strptime() argument 1 must be str, not None - Refers to not being able to fetch the datetime of the stream which is consistent with the 403 error.

**Comment by Shishkebaboo** [comment]
Linking #18..... both issues are related to the same 403 error due to anti bot detection.

**Comment by Shishkebaboo** [comment]
@mepherion Streamscharts seems to be accepting requests again. Im guessing this will happen again as sourcing from third parties is not always going to work. 

Script works as intended.
